# Generated by Django 5.2.6 on 2025-09-29 11:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant1App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img_prod',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
